name: cartedevisite
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  url_launcher: ^6.1.14
  flutter_secure_storage: ^9.2.4
  dio: ^5.0.0
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.2.0
  shared_preferences: ^2.0.14
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  email_validator: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  open_file: ^3.3.2
  path_provider: ^2.1.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons.png" # Remplacez par votre image
  adaptive_icon_background: "#ffffff" # Couleur de fond (pour Android 8+)
  adaptive_icon_foreground: "assets/icons.png" # Même image ou une version simplifiée